name: watchkeun
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.1
  get_it: ^7.6.7
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  flutter_bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  http_mock_adapter: ^0.6.1
  bloc_test: ^9.1.6
  mocktail: ^1.0.3
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/